# Site settings
title: Andrea Verlicchi's Blog
subtitle: A web craftsman's tech blog
email: andrea.verlicchi@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Andrea is a web craftsman, a father, a fan of GitHub and a proud writer of this tech blog.
  He currently works at YOOX NET-A-PORTER GROUP and he occasionally speaks at front-end conferences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.andreaverlicchi.eu" # the base hostname & protocol for your site
twitter_username: verlok
github_username:  verlok
markdown: kramdown
include: [.htaccess]
paginate: 20
google_analytics: UA-26756203-1
disqus:
  shortname: andreaverlicchi-blog
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: /:title/
gems: [jekyll-paginate]
