# Site settings
title: Andrea Verlicchi
subtitle: Web front-end development addicted
email: andrea.verlicchi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web front-end development addicted, Andrea currently works as front-end architect
  at Yoox Net-a-Porter Group and he's an occasional speaker at front-end conferences.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.andreaverlicchi.eu" # the base hostname & protocol for your site
twitter_username: verlok
github_username:  verlok
markdown: kramdown
exclude: [examples]
include: [.htaccess]
paginate: 10
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: /:title/
gems: [jekyll-paginate]
